server:
  port: 8456 # 端口号
  servlet:
    context-path: /api # 上下文路径
spring:
  profiles:
    active: local # 激活的配置文件
  application:
    name: visual-assets # 项目名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://118.31.62.68:3306/VisualAssets # 数据库地址
    username: ${DB_USERNAME} # 数据库用户名
    password: ${DB_PASSWORD} # 数据库密码